# Generated by Django 2.2.16 on 2022-06-10 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220610_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2022, 6, 10, 8, 50, 18, 631518, tzinfo=utc), verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
